### ISSUE TITLE
trying to run it locally, but hit a issue.

### ISSUE THREAD

**Issue by crypticsymmetry** [Dene33/video_to_bvh#16]
**windows 10**  , **python 3.6**
when running 3dpose_estimate.sh it will always get stuck.. right at ipdb
i changed python2 to python within 3dpose_estimate.sh.
i tried adding neutral_smpl_with_cocoplus_reg.pkl file and also moving it around to see if it would find it.  any ideas? can i add any other info that will help?
thanks

Processing ti10002                                                              
Fix path to models/                                                             
D:\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml .load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.                               
data = yaml.load(f.read()) or {}           
d:\machinelearning\3dpose\hmr-master\src\config.py(26)()                    
    25     ipdb.set_trace()                                                     
    ---> 26 SMPL_MODEL_PATH = osp.join(model_dir, 'neutral_smpl_with_cocoplus_reg.pkl')                                                                                   
    27 SMPL_FACE_PATH = osp.join(curr_path, '../src/tf_smpl', 'smpl_faces.npy')                                                                                                                                 
  ipdb>

**Comment by crypticsymmetry** [comment]
got past the last issue now ive hit this. 

 when running keras realtime multiperson estimation i get the following nameerror.. trying to get this working locally as well.

**Keras error ..**

`keras_Realtime_Multi-Person_Pose_Estimation>python 2d_pose_estimation.py --image 
Now proccessing: ti10001.jpg
Traceback (most recent call last):
  File "2d_pose_estimation.py", line 18, in <module>
    param, model_params = config_reader()
NameError: name 'config_reader' is not defined`

**Comment by crypticsymmetry** [comment]
added `from config_reader import config_reader` seemed to get rid of that issue, i think. 
 now i get.
 ```
Now proccessing: ti10001.jpg
Input shape: (1, 184, 328, 3)
Traceback (most recent call last):
  File "2d_pose_estimation.py", line 37, in <module>
    output_blobs = model.predict(input_img)
NameError: name 'model' is not defined
```
i have tried to import a few different things but cannot find the right one. any directions would be awesome. thanks!

**edit** added `from model_load import model` now runs

**Comment by crypticsymmetry** [comment]
**windows 10** , **python 3.6**
when running 3dpose_estimate.sh locally i get this error any ideas? sorry for all the comments.
had to change `import cPickle as pickle` to `import pickle`

```
File "demo.py", line 211, in <module>
    main(config.img_path, config.json_path)
  File "demo.py", line 125, in main
    model = RunModel(config, sess=sess)
  File "D:\MACHINELEARNING\video_to_bvh-master\hmr\src\RunModel.py", line 56, in __init__
    self.smpl = SMPL(self.smpl_model_path, joint_type=self.joint_type)
  File "D:\MACHINELEARNING\video_to_bvh-master\hmr\src\tf_smpl\batch_smpl.py", line 32, in __init__
    dd = pickle.load(f)
  File "D:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 235: character maps to <undefined>
```

**edit** i think i fixed it by adding 
```
with open(pkl_path, 'rb') as f:
            dd = pickle.load(f, encoding="latin-1")
```

**Comment by crypticsymmetry** [comment]
now i get this error.



**edit**  i tried again with xrange it will run and i get some csv files but i get this


Traceback (most recent call last):  
File "demo.py", line 211, in  main(config.img_path, config.json_path)   
File "demo.py", line 189, in main    visualize(img_path, img, proc_param, joints[0], verts[0], cams[0])           
File "demo.py", line 53, in visualize    skel_img = vis_util.draw_skeleton(img, joints_orig)                            File "D:\MACHINELEARNING\video_to_bvh-master\hmr\src\util\renderer.py", line 3 92, in draw_skeleton                                                                 for child in xrange(len(parents)):                                           
NameError: name 'xrange' is not defined

i have tried changing `xrange to range` but i think it gets stuck in a loop and never continues.



`Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wit h 6315 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id : 0000:07:00.0, compute capability: 7.5)                                         D:\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml .load() without Loader=... is deprecated, as the default Loader is unsafe. Pleas e read https://msg.pyyaml.org/load for full details.                               data = yaml.load(f.read()) or {}                                               W0717 14:17:08.603337  9480 deprecation.py:323] From D:\Anaconda3\lib\site-packa ges\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow .python.training.checkpoint_management) is deprecated and will be removed in a f uture version.                                                                   Instructions for updating:                                                       Use standard file APIs to check for files with this prefix.`

**Comment by amar8600** [comment]
> **windows 10** , **python 3.6**
> when running 3dpose_estimate.sh it will always get stuck.. right at ipdb
> i changed python2 to python within 3dpose_estimate.sh.
> i tried adding neutral_smpl_with_cocoplus_reg.pkl file and also moving it around to see if it would find it. any ideas? can i add any other info that will help?
> thanks
> 
> Processing ti10002
> Fix path to models/
> D:\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml .load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> data = yaml.load(f.read()) or {}
> d:\machinelearning\3dpose\hmr-master\src\config.py(26)()
> 25 ipdb.set_trace()
> ---> 26 SMPL_MODEL_PATH = osp.join(model_dir, 'neutral_smpl_with_cocoplus_reg.pkl')
> 27 SMPL_FACE_PATH = osp.join(curr_path, '../src/tf_smpl', 'smpl_faces.npy')
> ipdb>

how to install opendr in windows plz reply
