### ISSUE TITLE
tensorflow.contrib.slim error in "Process the video"

### ISSUE THREAD

**Issue by Adilrn** [Dene33/video_to_bvh#26]
I have followed the steps to  execute the  code but I keep having an issue regarding the processing. In fact, when executing the segment "process the video", it doesn't go through. This is how the execution ends:

Traceback (most recent call last):
  File "hmr/demo.py", line 33, in <module>
    from src.RunModel import RunModel
  File "/content/hmr/src/RunModel.py", line 13, in <module>
    from .models import get_encoder_fn_separate
  File "/content/hmr/src/models.py", line 19, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named contrib.slim
Done
Read blend: /content/hmr/csv_to_bvh.blend
[bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
Traceback (most recent call last):
  File "/content/hmr/csv_to_bvh.py", line 20, in <module>
    with open(fullpath, 'r', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

Blender quit
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f135b80e400 

Can anybody help me with this? I tried using tensorflow 1.3.0 ; 1.11 ;1.14 and finally 2.2.0. When using 1.3.0 an 1.11, I get a different error, the code doesn't even reach the point where it requires contrib.slim

**Comment by Ritchizh** [comment]
Hi! Try:
`!pip2 install tensorflow==1.5.0`
and restarting Runtime.

**Comment by Adilrn** [comment]
Thank you very much, it worked

**Comment by happyCodingSusan** [comment]
@Dene33 , impressive work! 

Do you run on Linux or Windows environment?
I tested your script on windows Chrome, and I did run "!pip2 install tensorflow==1.5.0" but still got the error of "FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv". 

In your read me file, you mentioned the change for runtime " Runtime > Change runtime type is Python 3 with GPU"
When I checked my "Runtime" settings, it only provides "Hardware accelerator" which allows me to change to "GPU". I did not find an option to choose "Python 3". Would it cause the error?

I wonder if you could point out anything that I can try.

Thanks very much for your kind reply!
