### ISSUE TITLE
visualize motion with bvh file

### ISSUE THREAD

**Issue by huiwenzhang** [Dene33/video_to_bvh#3]
Hi,

Thanks for sharing this. I successfully got the bvh file by following the steps you documented. I want to know how to visualize the motion in blender? Do I need to create a new human mesh file and then apply the motion to it? Besides, is there any way to convert the bvh file to ARM format file or can we directly output the AMC file by using the hmr?

Thanks

**Comment by Dene33** [comment]
0. Open Blender, select Cube with right click and delete it;
1. File > Import > Motion Capture (.bvh);
2. Alt+A to play imported .bvh animation

I'm not sure about ARM and AMC file formats. Could you provide a little bit more info? Thanks.
