### ISSUE TITLE
csv_joined key pionts type

### ISSUE THREAD

**Issue by Adilrn** [Dene33/video_to_bvh#30]
Hello, I have been thinking about using the key points in the final CSV join file to animate an avatar in Unity and I would like to know if anyone here has tried it already and if it is feasible. Is the x, y and z obtained, rotation or position point?

**Comment by zq1335030905** [comment]
yes, It can work. the csv join file contains x,y,z obtained and not includes rotation. at last i can generate a bvh file and can be showned in blender player.

**Comment by Adilrn** [comment]
Thank you. But I wonder how one could achieve some animation that looks like the initial  video in Unity as there is no rotation info? Any post that could guide me through that?
