### ISSUE TITLE
FileNotFoundError Due to [Choose Files] Button the Upload Widget is not Available Even the Session is Rerun

### ISSUE THREAD

**Issue by markchang2006** [Dene33/video_to_bvh#31]
2 error messages are shown below for your information:

1>
MessageError                              Traceback (most recent call last)
<ipython-input-14-bf54d305a1f6> in <module>()
      1 #upload video
----> 2 exec(open('upload_videos.py').read())

<string> in <module>()

2>
/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

Another Error Message is shown after the {Upload Video] cell is rerun as below:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-25-bf54d305a1f6> in <module>()
      1 #upload video
----> 2 exec(open('upload_videos.py').read())

FileNotFoundError: [Errno 2] No such file or directory: 'upload_videos.py'

It happens even though I've rerun the Upload Video, the cell has been re-executed in the current browser session, agin and again.

Please help. Thanks!

**Comment by ag2s20150909** [comment]
It sounds like third-party cookies may be disabled in your browser, see https://github.com/googlecolab/colabtools/issues/17.

The setting is under chrome://settings/content/cookies.

**Comment by markchang2006** [comment]
Thanks for your prompt and kind support! The problem is solved. Thanks a lot!
