### ISSUE TITLE
CSV to blend error

### ISSUE THREAD

**Issue by aitorgutierrez** [Dene33/video_to_bvh#4]
Hello!

When I execute "blender --background hmr/csv_to_bvh.blend -noaudio -P hmr/csv_to_bvh.py" to convert .csv files to bvh, I am always getting the same error in different videos:

```
BVH Exported: hmr/output/bvh_animation/estimated_animation.bvh frames:251

Error, region type 4 missing in - name:"Action", id:12
Error, region type 4 missing in - name:"Action", id:12

Blender quit

```
It only export 251 frames, why is this happing? But I have more than 1000K frames, it always stops here

Thanks in advance

**Comment by Dene33** [comment]
Fixed. Redownload this file: https://github.com/Dene33/hmr/blob/master/csv_to_bvh.py and try again. If everything works fine, let me know. Thanks.

**Comment by mariolew** [comment]
Problem still exists with new scripts

**Comment by xinzi2018** [comment]
i have the same problem!
