### ISSUE TITLE
Frame limit to 250?

### ISSUE THREAD

**Issue by noumanriazkhan** [Dene33/video_to_bvh#5]
Hi,

Thanks for the awesome script.

I have been trying to animate a larger frame sequence (1500 appx) but the resulting animation is only 250 frames long.

'BVH Exported: ./estimated_animation.bvh frames:251'

and no error. Can you guide me through fixing this?

Thanks

**Comment by mariolew** [comment]
@noumanriazkhan How did you solve this?

**Comment by noumanriazkhan** [comment]
@mariolew turned out that blender defaults it to 250, just change it there.
