### ISSUE TITLE
Instructions on running python version locally ? 

### ISSUE THREAD

**Issue by timtensor** [Dene33/video_to_bvh#9]
Hi , 
i had some issues with running your `google collab` notebook. So i looked in your python code 
[https://github.com/Dene33/hmr](url)

I am trying to follow the steps as you mentioned in the `notebook` but i failed to run a video sequence on it,  Is there a guide on how to run a video and get the mesh for the above mentioned repository ?  `hmr`  
As instructed the pretrained model has ben downloaded to the `model` directory . 
Thanks!

**Comment by Dene33** [comment]
If you run it locally you should install all the dependencies and CUDA drivers for your Nvidia GPU.

**Comment by crypticsymmetry** [comment]
@timtensor did you get it to run locally? if so, how did you do it? thanks
